
Database related
https://www.youtube.com/watch?v=tv-_1er1mWI
https://jsonformatter.org/json-viewer
http://perso.modulonet.fr/~placurie/Ressources/BTS1-Cgo1/Chap_6_Dictionnaire_des_donnees.pdf
http://icps.u-strasbg.fr/~genaud/courses/webtech/php/ch06.html
https://mosaika.fr/creer-table-sql-wordpress-commission/
http://www.dynamic-mess.com/developpement/mcd-mdd-mpd-dessiner-sa-bdd/
https://fsmrel.developpez.com/basesrelationnelles/workbench/?page=2#L2-2
http://cours.pise.info/modelisation/merise.htm
https://www.javascripttutorial.net/javascript-return-multiple-values/
https://www.mysql.com/fr/products/workbench/
https://www.eclipse.org/papyrus/
https://refactoring.guru/fr/design-patterns
Docs tech
https://developer.mozilla.org/fr/docs/Web/CSS/@charset
https://developer.mozilla.org/fr/docs/Web/CSS/@font-face
https://developer.mozilla.org/fr/docs/Web/CSS/@import
https://www.pierre-giraud.com/javascript-apprendre-coder-cours/dom-acces-modification/
https://daringfireball.net/projects/markdown/syntax
https://www.pierre-giraud.com/javascript-apprendre-coder-cours/definition-creation-constructeur/
https://developer.mozilla.org/fr/
https://code.visualstudio.com/docs
https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Expressions_et_Op%C3%A9rateurs
https://doc.ubuntu-fr.org/fichier_cache
https://git-scm.com/doc
https://michelf.ca/projets/php-markdown/syntaxe/
https://www.pierre-giraud.com/
https://www.w3schools.com/
Frameworks
https://animate.style/
https://fr.reactjs.org/
https://angular.io/
https://vuejs.org/
https://jquery.com/
Front
Bootstrap
https://freefrontend.com/bootstrap-buttons/
https://www.bootstarters.com/
https://www.layoutit.com/build#
https://www.youtube.com/watch?v=23bpce-5s8I
https://mdbootstrap.com/docs/standard/components/collapse/
https://getbootstrap.com/docs/5.2/examples/
https://medium.com/@sreejithezhakkad/how-to-start-a-web-app-project-using-bootstrap-with-npm-webpack-185e510a782e
https://tutowebdesign.com/les-composants-bootstrap.php
https://www.youtube.com/watch?v=68O6eOGAGqA
CSS
BEM-OOCSS
https://www.alsacreations.com/article/lire/1641-Bonnes-pratiques-en-CSS--BEM-et-OOCSS.html
https://en.bem.info/methodology/key-concepts/#naming-for-independent-css-classes
https://jaetheme.com/methode-integration-html/
https://www.design-fluide.com/21-09-2011/le-css-oriente-objet-explique-avec-monsieur-patate/
https://putaindecode.io/articles/petite-definition-de-bem/
https://www.nicoespeon.com/fr/2013/05/plongee-au-coeur-de-oocss/
https://100dayscss.com/
https://freefrontend.com/css-toggle-menus/
https://www.web-eau.net/blog/15-effets-css3-pour-vos-images
https://css-tricks.com/snippets/css/a-guide-to-flexbox/
https://fr.w3docs.com/snippets/css/how-to-vertically-center-text-with-css-1.html
https://dev.to/devmount/8-games-to-learn-css-the-fun-way-4e0f
http://howtocenterincss.com/
https://www.youtube.com/watch?v=S-W0NX97DB0
https://codepen.io/matmarsiglio/pen/pojoPR
https://codepen.io/hrtzt/pen/NPZKRN
https://codepen.io/_fbrz/pen/bNdMwZ
https://codepen.io/EduardL/pen/aBGAy
https://codepen.io/JFarrow/pen/fFrpg
https://html-css-js.com/css/generator/font/
https://codingislove.com/image-caption-hover-effect/
Template web homepage
https://onepagelove.com/avocado
https://onepagelove.com/ayro-business
https://milton-template.webflow.io/
https://onepagelove.com/browny
https://onepagelove.com/chippewa
https://demo.w3layouts.com/demos_new/30-01-2017/dance_whirl-demo_Free/785171594/web/index.html
https://onepagelove.com/dazzle
https://html5up.net/uploads/demos/dimension/
https://onepagelove.com/dribbblefolio
https://onepagelove.com/essence-lite
https://onepagelove.com/templates/free-templates/page/11
https://onepagelove.com/helium
https://onepagelove.com/huddle
https://onepagelove.com/integral-lite
https://bootstrapmade.com/demo/iPortfolio/
https://onepagelove.com/justice
https://onepagelove.com/rife
https://onepagelove.com/mate
https://bootstrapmade.com/demo/MyResume/
https://onepagelove.com/namari
https://html5up.net/uploads/demos/paradigm-shift/
https://pompeo.webflow.io/
https://onepagelove.com/serenity-lite
https://tigertells.fun/
https://onepagelove.com/yebo
https://technext.github.io/barberz/index.html
http://preview.themeforest.net/item/lydia-photography-magazine-site-template/full_screen_preview/12931793?clickid=wCPzdD3gDxyLRMDwUx0Mo3EtUkEWTIRVhSrQUo0&iradid=275988&iradtype=ONLINE_TRACKING_LINK&irgwc=1&irmptype=mediapartner&irpid=369282&mp_value1=&utm_campaign=af_impact_radius_369282&utm_medium=affiliate&utm_source=impact_radius
https://startbootstrap.com/previews/clean-blog
https://pfolios.net/?ref=collectui
https://cherupil.com/
Wordpress
https://kinsta.com/fr/base-de-connaissances/ajouter-code-wordpress-header-footer/#manual
https://www.undefined.fr/comment-creer-un-module-wordpress
https://www.lafabriquedunet.fr/blog/meilleurs-tutoriels-wordpress/
https://blog.wplauncher.com/add-custom-database-table-to-a-wordpress-plugin/
https://www.wpbeginner.com/wp-themes/how-to-add-custom-navigation-menus-in-wordpress-3-0-themes/
https://openclassrooms.com/fr/courses/5489551-creez-un-site-moderne-et-professionnel-avec-wordpress-5?archived-source=1891206
https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/
Elementor
https://app.infinityfree.net/login
https://www.reddit.com/r/webdev/comments/wngz49/i_recreated_this_panning_image_gallery_effect_and/
https://fr.wikihow.com/ins%C3%A9rer-des-espaces-dans-un-code-HTML
https://m.youtube.com/watch?v=vSEcBiyNe8Y
https://montrezvous.net/developpement-web/controles-de-formulaires-en-html5.html
https://www.pierre-giraud.com/javascript-apprendre-coder-cours/validation-formulaire/
https://headway.io/event-series/figma-tutorials-for-beginners
https://fontawesome.com/
https://www.youtube.com/watch?v=C2Owc8BPdbs
https://www.flaticon.com/
https://www.frontendmentor.io/
https://fonts.google.com/
https://medium.com/@agavitalis/how-to-deploy-a-simple-static-html-website-on-heroku-492697238e48
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
https://www.toptal.com/designers/htmlarrows/symbols/
https://blog.mailtrap.io/html5-email-validation-tutorial/
https://webdesign.tutsplus.com/tutorials/html5-form-validation-with-the-pattern-attribute--cms-25145
https://html5up.net/
https://www.canva.com/fr_fr/decouvrir/identite-visuelle/
https://www.tutorialrepublic.com/css-reference/css3-properties.php
https://www.materialpalette.com/colors
https://www.materialui.co/colors
https://codepen.io/GeoffreyCrofte/pen/oCBxz
https://uiverse.io/
https://www.creativejuiz.fr/blog/tutoriels/personnaliser-aspect-boutons-radio-checkbox-css
https://codepen.io/erikterwan/pen/EVzeRP
http://gabrielbraun.free.fr/2017/TechWeb/index.php?rubrique=HTML5&chapitre=01_HTML5&id=05&css=0&page=forms
https://icones8.fr/
https://material.io/design/color/the-color-system.html#tools-for-picking-colors
https://fr.freepik.com/
https://collectui.com/
https://codepen.io/
https://cdnjs.com/libraries/font-awesome
https://fontinterceptor.mschfmag.com/
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial
https://www.youtube.com/watch?v=zLh0K1PdUbc
https://www.youtube.com/channel/UCDo7RTzizoOdPjY8A-xDR7g
https://thebookofshaders.com/
https://threejs-journey.com/?c=p3
https://daftpage.com/
https://intab.io/resources/
https://dribbble.com/
https://jamessapp.medium.com/dom-cheat-sheet-ae4bf2299bee
https://validator.w3.org/
Gestion de projet
https://trello.com/vincentfravette1/boards
https://www.aubryconseil.com/post/2007/la-r%C3%A9trospective-de-sprint/
https://agiliste.fr/art-de-la-retrospective/
https://www.cadremploi.fr/editorial/conseils/conseils-carriere/detail/article/jose-pas-demander-mais-quest-ce-que-la-methode-agile.html
https://www.cadremploi.fr/editorial/conseils/conseils-carriere/detail/article/jose-pas-demander-mais-c-est-quoi-la-methode-kanban.html
https://blog.trello.com/fr/comment-utiliser-trello
https://www.scrumguides.org/index.html
https://www.atlassian.com/fr/agile/kanban/boards
https://www.atlassian.com/fr/agile/kanban
https://www.thierry-pigot.fr/scrum-en-moins-de-10-minutes/
https://www.atlassian.com/fr/agile/scrum
https://www.nutcache.com/fr/blog/methodologie-scrum/
https://certifagile.com/free-psm1-assessment/
https://medium.com/bewizyu/tout-sur-les-certifications-agile-scrum-org-fcf9303e2b22
Git related
https://www.onasus.com/10-commandes-utiles-de-git-a-connaitre/
http://codeur-pro.fr/acceder-en-ssh-a-vos-depots-git-distants-github/
https://lhauspie.wordpress.com/2018/06/26/configuration-git-le-bon-mail-pour-le-bon-repo/
https://www.christopheducamp.com/2013/12/16/creer-un-repo-github/
https://www.miximum.fr/blog/enfin-comprendre-git/
https://rogerdudler.github.io/git-guide/index.fr.html
https://git-scm.com/book/fr/v2/Les-bases-de-Git-Travailler-avec-des-d%C3%A9p%C3%B4ts-distants
https://dvic.devinci.fr/resource/tutorial/github-les-bases/
https://www.fxparlant.net/github-ajouter-un-projet-deja-cree/
https://mhagemann.medium.com/how-to-fix-ssh-permission-denied-with-git-clone-f669b65f90ac
https://www.hostinger.fr/tutoriels/commandes-git/
https://blog.zenika.com/2017/01/24/pull-request-demystifie/
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
https://gist.github.com/YannBouyeron/7f7c5486b5daa20c2a6080f67b2af344
https://git-scm.com/docs/git-check-ignore
https://www.kunal-chowdhury.com/p/git-cheatsheet.html
https://www.toptal.com/developers/gitignore
http://kinolien.github.io/gitzip/
Gitlab
https://www.baeldung.com/ops/gitlab-runner-guide
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-gitlab-on-ubuntu
Javascript
https://itnext.io/javascript-development-making-a-web-worker-optional-f23a13490b28
https://m.youtube.com/watch?v=5sNXjRE1C-U
https://medium.com/before-semicolon/25-javascript-code-solutions-utility-tricks-you-need-to-know-about-3023f7ed993e
https://www.freecodecamp.org/news/javascript-projects-for-beginners/#how-to-create-a-color-flipper
https://medium.com/before-semicolon/50-javascript-best-practice-rules-to-write-better-code-86ce731311d7
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array
https://www.youtube.com/watch?v=Ttf3CEsEwMQ
https://www.youtube.com/watch?v=3PHXvlpOkf4&t=1825s
https://www.youtube.com/watch?v=G1eW3Oi6uoc
https://www.youtube.com/watch?v=fxY1q4SCB64
https://www.youtube.com/watch?v=DFhmNLKwwGw
https://www.youtube.com/watch?v=Yw-SYSG-028
https://www.youtube.com/watch?v=wPElVpR1rwA
https://www.youtube.com/watch?v=XuFDcZABiDQ
https://www.youtube.com/watch?v=bxWsZTtqs80
https://www.reddit.com/r/learnjavascript/comments/by03v2/buttons_without_onclick/
https://adrienjoly.com/cours-javascript/
https://stackoverflow.com/questions/5786851/define-a-global-variable-in-a-javascript-function
https://blog.nicolas.brondin-bernard.com/etudier-la-programmation-a-harvard-stanford-ou-au-mit-gratuitement/amp/
https://www.w3schools.com/php/exercise.asp?filename=exercise_arrays5
https://www.youtube.com/watch?v=CI2GwL--ll8
https://stackoverflow.com/questions/32546100/how-to-write-data-to-a-json-file-using-javascript
https://stackoverrun.com/fr/q/2815230
https://stackoverflow.com/questions/14220321/how-to-return-the-response-from-an-asynchronous-call
https://stackoverflow.com/questions/23667086/why-is-my-variable-unaltered-after-i-modify-it-inside-of-a-function-asynchron
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics
https://www.youtube.com/watch?v=M2bJBuaOeOQ
https://www.codingcommanders.com/dice/javascript-fetch-high-score-list.html
https://www.youtube.com/watch?v=rRgD1yVwIvE
https://exercism.org/tracks/javascript/exercises
https://www.youtube.com/watch?v=DHvZLI7Db8E
https://stackoverflow.com/questions/1860675/jquery-clear-form-on-close)
https://learnxinyminutes.com/docs/javascript/
https://jeremymouzin.com/blog/les-points-virgules-en-javascript-le-guide-definitif/
https://www.youtube.com/channel/UC56l7uZA209tlPTVOJiJ8Tw
https://www.youtube.com/watch?v=NYq9J-Eur9U
https://www.youtube.com/watch?v=POX3dT-pB4E
https://www.youtube.com/watch?v=FiGmAI5e91M
https://www.youtube.com/watch?v=Ke90Tje7VS0
https://www.youtube.com/watch?v=w7ejDZ8SWv8
https://www.textfixer.com/tutorials/javascript-line-breaks.php
https://www.educba.com/sorting-algorithms-in-javascript/
https://devhints.io/moment
https://codepen.io/Akimzzy/pen/JjGKMoX
https://www.ditdot.hr/en/4-tips-better-asynchronous-javascript-code
https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/
Jeux
https://www.codewars.com/dashboard
http://flexboxfroggy.com/#fr
https://codepip.com/
https://blockly.games/?lang=fr
https://exercism.org/
PHP
https://www.univ-orleans.fr/iut-orleans/informatique/intra/tuto/php/FastPHP.pdf
https://www.tutorialrepublic.com/php-tutorial/php-mysql-login-system.php
https://m.youtube.com/watch?v=-NYKvQqI1TA
https://xpertphp.com/crud-operation-using-json-file-in-php/
https://www.codingame.com/playgrounds/32339/exercices-de-php-pour-debutant
https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-18-04
https://www.sitepoint.com/how-to-install-php-on-windows/
https://laravel.com/docs/8.x
https://laracasts.com/series/laravel-8-from-scratch
https://github.com/laravel/laravel
https://nouvelle-techno.fr/actualites/live-coding-creer-un-crud-en-php
https://www.tutorialspoint.com/php/php_login_example.htm
http://www.poussenews.fr/25-php-js-lire-ecrire-bases-de-donnees-json
https://www.w3schools.com/php/php_includes.asp
https://www.sitepoint.com/docker-php-development-environment/
https://linuxhint.com/laravel_dev_debian_10/
https://dev.to/truthseekers/setup-a-basic-local-php-development-environment-in-docker-kod
https://www.youtube.com/watch?v=DWHZSkn5paQ
https://openclassrooms.com/fr/courses/918836-concevez-votre-site-web-avec-php-et-mysql/913099-transmettez-des-donnees-avec-les-formulaires
https://fabien-torre.fr/Enseignement/tp/PHP/
https://www.copier-coller.com/un-crud-en-php/
https://stackoverflow.com/questions/27766441/unable-to-show-session-message-in-php
https://www.numelion.com/utiliser-manipuler-fichier-json-php.html
https://rappasoft.com/quizzes/laravel
https://docs.joomla.org/Configuring_a_LAMPP_server_for_PHP_development/Linux_desktop
Ressources dev
https://www.youtube.com/watch?v=gKMYZi4j_YU
https://dmitripavlutin.com/operations-on-arrays-javascript/
https://www.cartelis.com/blog/exemples-formulaires-design/
https://newflux.fr/2017/10/22/30-bonnes-pratiques-astuces-vos-formulaires/
https://github.com/alexmacarthur/slide-element
https://animista.net/play/exits/puff-out
https://michalsnik.github.io/aos/
https://unsplash.com/
https://jsonformatter.org/jsbeautifier
https://stackoverflow.com/questions/32902472/can-i-host-my-wordpress-blog-on-github-pages-as-a-static-webpage
https://caniuse.com/input-datetime
https://www.kaherecode.com/tutorial/comment-documenter-son-api-laravel-via-openapi-swagger
https://cs50.harvard.edu/x/2022/
https://dev.to/
https://www.hywel.me/static/site/wordpress/2016/07/17/fast-free-static-website-with-wordpress-and-github-pages.html
https://www.fiverr.com/
https://www.hostinger.com/?utm_medium=affiliate&utm_source=aff90137&utm_campaign=264&session=102e4870ec926a7cbe773a04c1f9fb
https://www.ovhcloud.com/fr/web-hosting/personal-offer/
https://www.techrepublic.com/article/how-to-create-locally-signed-ssl-certificates-with-mkcert/
https://jsonlint.com/
http://keepnote.org/
https://developer.mozilla.org/fr/docs/Learn/JavaScript/Objects/JSON
https://flow.microsoft.com/fr-fr/
https://www.nylas.com/
https://www.colourlovers.com/palette/624420/Pre-Disaster
https://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF
https://www.pexels.com/fr-fr/
https://www.pierre-giraud.com/javascript-apprendre-coder-cours/json/
https://codepen.io/webd3v/pen/JbJvMQ
https://tinyjpg.com/
https://www.youtube.com/watch?v=Xa5EU-qAv-I
https://www.wirify.com/
https://buffer.com/library/free-seo-tools/
https://www.tablesgenerator.com/markdown_tables
https://anywaydata.com/
https://draw.io/
https://www.blackbox.ai/
https://www.reddit.com/r/coolguides/comments/wxoq10/how_to_enhance_your_google_searches/
https://leetcode.com/
Scrapping
https://docs.scrapingrobot.com/reference/basic-usage
https://choualbox.com/eFlJj
https://proxycrawl.com/blog/how-to-scrape-data-from-google-maps/
https://proxycrawl.com/dashboard
https://helpcenter.octoparse.com/hc/en-us/articles/360018842111-Scrape-data-in-Google-Maps#div1
https://medium.com/data-scraper-tips-tricks/scraping-data-with-javascript-in-3-minutes-8a7cf8275b31
https://www.scrapingbee.com/blog/web-scraping-javascript/
https://www.scrapingbee.com/blog/web-scraping-php/
https://www.youtube.com/watch?v=TzZ3YOUhCxo
https://apify.com/
Veille
https://www.jobteaser.com/fr/advices/180-3-etapes-pour-se-presenter-en-3-minutes-en-entretien
https://www.cadremploi.fr/editorial/conseils/conseils-candidature/entretien-embauche/detail/article/cinq-points-cles-pour-faire-bonne-impression-en-entretien.html
https://www.turn-on.fr/blog/bien-rediger-ses-user-stories
https://blockly-demo.appspot.com/static/demos/code/index.html?lang=fr#
https://web.iamvdo.me/js/exercices/validation-formulaire/
https://jsfunctionnal.blogspot.com/2009/01/tris-en-javascript.html
https://kinsta.com/fr/blog/site-portfolio/
https://www.pole-emploi.fr/candidat/vos-recherches/bien-vous-organiser/lart-de-se-presenter-en-5-minute.html
https://mrproof.blogspot.com/2011/02/le-dictionnaire-des-donnees-cours.html
https://www.economie.gouv.fr/entreprises/reglement-general-sur-protection-des-donnees-rgpd
http://blog.nethik.fr/2009/08/le-w3c-ou-lorganisme-de-normalisation-du-web/
https://www.lafabriquedunet.fr/creation-site-vitrine/articles/wireframing-guide-complet-maquettes-fonctionnelles-web/
https://developer.mozilla.org/fr/docs/Web/CSS/Requ%C3%AAtes_m%C3%A9dia/Utiliser_les_Media_queries
https://medium.com/@JeremyRaffin/site-web-statique-optimis%C3%A9-avec-github-pages-cr%C3%A9ation-du-d%C3%A9p%C3%B4t-et-activation-de-github-pages-1-4-2537061ef3dd
https://lafabriquedeblogs.com/blogue/guide-wireframe/
https://donnees-rgpd.fr/traitement-donnees/
https://www.ionos.fr/digitalguide/hebergement/aspects-techniques/quest-ce-que-lhebergement-web/
https://www.lemagit.fr/definition/Cluster
https://www.service-public.fr/professionnels-entreprises/vosdroits/F31228
https://www.cnil.fr/fr/rgpd-de-quoi-parle-t-on
https://www.cnil.fr/fr/rgpd-par-ou-commencer
https://www.monster.ch/fr/conseil-carriere/article/savoir-se-presenter-en-2-minutes-chrono-chfr-30410
https://www.webaxones.com/service/site-internet-normes-standards/
https://www.atlassian.com/fr/agile/project-management/user-stories
https://esokia.com/fr/blog/ux-ui-quest-ce-que-ca-signifie
https://developer.mozilla.org/fr/docs/Web/Guide/HTML/Formulaires/Validation_donnees_formulaire
https://www.ionos.fr/digitalguide/sites-internet/developpement-web/quest-ce-que-le-builder-pattern/
https://tympanus.net/codrops/
https://www.emse.fr/~picard/cours/2A/DesignPatternsISI.pdf
https://www.jmdoudoux.fr/java/dej/chap-design-patterns.htm
https://blog.nicolas.brondin-bernard.com/les-podcasts-incontournables-pour-les-developpeurs-en-francais/
https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/
https://blog.nicolas.brondin-bernard.com/
https://www.theodinproject.com/
https://projecteuler.net/
https://www.stratascratch.com/
https://www.youtube.com/watch?v=Dk6Wopar10k
https://www.youtube.com/channel/UCFbNIlppjAuEX4znoulh0Cw
https://wizardzines.com/
https://yare.io/
https://christianheilmann.com/2021/11/01/developer-tools-secrets-that-shouldnt-be-secrets/
https://teachyourselfcs.com/2016/
https://web.stanford.edu/class/cs253/
https://tryhackme.com/
https://archive.org/details/ucberkeley-webcast-PL3E89002AA9B9879E?sort=titleSorter
https://andreasbm.github.io/web-skills/
https://sp19.datastructur.es/
https://www.youtube.com/playlist?list=PLpPXw4zFa0uKKhaSz87IowJnOTzh9tiBk
https://id.heroku.com/login
https://stackoverflow.com/
https://github.com/
https://pragprog.com/
Github repositories
https://github.com/godcrampy/cheat-sheets/
https://github.com/FiloSottile/mkcert#installation
https://github.com/jamesqquick/javascript-array-functions-practice
https://github.com/jlevy/the-art-of-command-line#readme
https://github.com/Mukosame/Anime2Sketch
https://github.com/tayllan/awesome-algorithms
https://github.com/trailofbits/algo#deploy-the-algo-server
https://github.com/xme/pfaudit
https://github.com/damienbelveze/formation_obsidian/blob/main/Mode%20d'emploi%20d'Obsidian.md
https://github.com/piotrplenik/clean-code-php
https://github.com/kamranahmedse/developer-roadmap
https://github.com/EbookFoundation/free-programming-books
https://github.com/vitalysim/Awesome-Hacking-Resources
https://pythontutor.com/visualize.html#mode=edit
https://www.blackbox.ai/?explore=true
https://ss64.com/
Powershell
https://blog.netwrix.fr/2018/09/26/tutoriel-de-windows-powershell-scripting-pour-debutants/
http://www.powershell-scripting.com/index.php?option=com_content&task=section&id=5&Itemid=71
https://www.it-connect.fr/powershell-pour-les-debutants-1ere-partie/
https://deployadmin.com/2018/11/04/quelques-cmdlet-powershell-utiles/
https://activedirectorypro.com/powershell-commands/
https://www.it-connect.fr/cours/apprendre-powershell-pour-les-debutants/
https://www.powershellcenter.com/2021/03/09/manage-ad-user-logon-hours-using-powershell/#Understanding_Logon_Hours_LogonHours_Basics
https://devblogs.microsoft.com/scripting/weekend-scripter-use-powershell-to-get-add-and-remove-ntfs-permissions/
https://www.it-connect.fr/chapitres/recuperer-des-informations-sur-les-utilisateurs-avec-powershell/
https://www.computerperformance.co.uk/powershell/environmental-variables/
https://github.com/dockur/samba
https://dev.to/ansonlowzf/learning-to-be-a-mouse-less-web-developer-7em
https://stackoverflow.com/questions/9844082/how-to-create-a-new-git-repository-from-an-existing-one
https://codepen.io/riazxrazor/pen/Gjomdp
https://workik.com/
https://github.com/MeresseAntoine1B2/python-cours/tree/main
https://kinsta.com/fr/blog/fastapi/
https://www.243tech.com/raccourcis-vs-code/
https://blog.ironmansoftware.com/daily-powershell/bash-powershell-cheatsheet/